name: RPGSkillsPlugin
version: 1.1
main: org.frizzlenpop.rPGSkillsPlugin.RPGSkillsPlugin
api-version: 1.21
author: Frizzlenpop
config-yml: config.yml
depend: [Vault]
softdepend: [ProtocolLib]

commands:
  skills:
    description: Opens the skills menu.
    usage: /skills
    permission: rpgskills.use
  passives:
    description: Opens the passive skills menu.
    usage: /passives
    permission: rpgskills.passive
  skilltree:
    description: Opens the skill tree menu or manages skill tree points.
    usage: /skilltree [info|unlock|level]
    permission: rpgskills.skilltree
  miningburst:
    description: Activates the Mining Burst ability.
    usage: /miningburst
    permission: rpgskills.miningburst
  timberchop:
    description: Activates the Timber Chop ability.
    usage: /timberchop
    permission: rpgskills.timberchop
  berserkerrage:
    description: Activates the Berserker Rage ability.
    usage: /berserkerrage
    permission: rpgskills.berserkerrage
  superharvest:
    description: Activates the Super Harvest ability
    usage: /superharvest
    permission: rpgskills.superharvest
  instantcatch:
    description: Activates the Instant Catch ability
    usage: /instantcatch
    permission: rpgskills.instantcatch
  doubleenchant:
    description: Activates the Double Enchant ability
    usage: /doubleenchant
    permission: rpgskills.doubleenchant
  toggleskillmessages:
    description: Toggle skill-related messages on/off
    usage: /toggleskillmessages
  skillsadmin:
    description: Admin commands for managing skills
    usage: /skillsadmin <player> <skill> <set/add> <level/xp> <amount>
    permission: rpgskills.admin
  abilities:
    description: Activate skill abilities
    usage: /abilities <skill>
  rstat:
    description: Display all XP boosts from skills and skill tree systems
    usage: /rstat
    permission: rpgskills.rstat
  rparty:
    description: Create and manage parties for XP sharing
    usage: /rparty [create|invite|accept|leave|disband|kick|list|share]
    permission: rpgskills.party
  rscoreboard:
    description: Toggle the RPG skills scoreboard visibility
    usage: /rscoreboard
    permission: rpgskills.scoreboard
  rpgbooster:
    description: Admin command to apply XP boosters to tools
    usage: /rpgbooster [apply|remove|check|help]
    permission: rpgskills.admin.xpbooster
  mount:
    description: Mount system commands
    usage: /mount <subcommand>
    aliases: [mounts]
    permission: rpgskills.mount.use
  mountchest:
    description: Mount chest and key system commands
    usage: /mountchest [open|keys|give|editrate]
    aliases: [mchest]
    permission: rpgskills.mount.chest
  rpghub:
    description: Opens the centralized RPG Hub menu
    usage: /rpghub
    aliases: [hub, rpg]
    permission: rpgskills.hub
  rpgdb:
    description: Database management commands
    usage: /rpgdb [status|migrate|help]
    aliases: [db]
    permission: rpgskills.admin

permissions:
  rpgskills.mount.use:
    description: Allows using the mount system
    default: true
  
  rpgskills.mount.admin:
    description: Allows access to mount admin commands
    default: op
    
  rpgskills.hub:
    description: Allows access to the RPG Hub menu
    default: true
    
  rpgskills.admin:
    description: Allows access to admin commands
    default: op